### ISSUE TITLE
RA execution is broken - 

### ISSUE THREAD

**Issue by RahulMR42** [oracle-devrel/terraform-oci-arch-devops-deployment-strategies#7]
Error while executing RA  -looks like its coming from OKE module 
--------------

Error: Unsupported argument
  on oke.tf line 31, in module "oci-oke" 
  31:   availability_domain                                                         = data.oci_identity_availability_domains.ADs.availability_domains[0]["name"]
An argument named "availability_domain" is not expected here. 

Please fix it ,thank you

**Comment by lfeldman** [comment]
@RahulMR42 We have fixed the underlying OKE remote module with [this release](https://github.com/oracle-devrel/terraform-oci-arch-oke/releases/tag/v1.2). Could you please restest it?

**Comment by RahulMR42** [comment]
thank you @lfeldman its working like charm !
