### ISSUE TITLE
Unable to run the stack on an existing cluster

### ISSUE THREAD

**Issue by ssp0** [oracle-devrel/terraform-oci-arch-devops-deployment-strategies#9]
```
Error: local-exec provisioner error
  with null_resource.oke_nginix_setup,
  on oke.tf line 80, in resource "null_resource" "oke_nginix_setup" 
  80:    provisioner "local-exec" {
Error running command 'echo '(1) Create namespace: '; export
KUBECONFIG=./generated/kubeconfig;kubectl create ns nsgreen;kubectl create ns
nsblue': exit status 1. Output: (1) Create namespace:
Error from server (AlreadyExists): namespaces "nsgreen" already exists
Error from server (AlreadyExists): namespaces "nsblue" already exists
```

**Comment by RahulMR42** [comment]
Hi @ssp0 
As you may see in the error the cluster has existing namespaces 'nsgreen' and 'nsblue' respectively and hence it's conflicting with the default config. So in this, you can set a preferable namespace name via stack Configure Variable options 

<img width="937" alt="image" src="https://user-images.githubusercontent.com/23480999/177139681-2502b06f-9a95-4050-8c0c-2fa66e627ef8.png">

- You may do this while creating the stack (second step) or using Edit variable screen under an existing stack.

Thank you

**Comment by RahulMR42** [comment]
Closing as there is no further response/query
